name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Emacs - ${{ matrix.emacs }}
    strategy:
      matrix:
        emacs: [26.1, 26.2, 26.3, 27.1, snapshot]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs }}

      - name: paths
        run: |
          echo "$HOME/.cask/bin" >> $GITHUB_PATH

      - name: Install cask
        run: |
          curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
          cask

      - name: Run a multi-line script
        run: |
          emacs --version
          make test
